version: "2.0"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # ports:
    #   - 270017:27017
    volumes:
      - ./mongo/db:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # ports:
    #   - 8081:8081
    depends_on:
      - mongo

  nginx:
    container_name: nginx
    image: mongo:latest
    restart: always
    # ports:
    #   - 80:80
    depends_on:
      - mongo
  
  frontend:
    command: npm run start
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: kerkoleng/golada-frontend:latest
    ports:
      - 8080:3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: kerkoleng/golada-backend:latest
    depends_on:
      - mongo
