version: "2.0"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    # ports:
    #   - 270017:27017
    volumes:
      - /home/tmp:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    # ports:
    #   - 8081:8081
    depends_on:
      - mongo

  nginx:
    container_name: nginx
    image: mongo:latest
    restart: always
    # ports:
    #   - 80:80
    depends_on:
      - mongo